defaults: 
- _self_
- task: toy_example
- action: ???
- model: fc

seed: ???
ntrain: 50000
num_action_samples_train: 10
num_action_samples_val: 10
sample_in_loop: False
data_dir: ../data/
res_dir: ../results/
experiment: ???