defaults: 
- _self_
- task: toy_example
- action: ???
- model: fc

seed: ???
ntrain: 50000
num_action_samples_train: 1
num_action_samples_val: 10
sample_in_loop: True
data_dir: ../data/
res_dir: ../results/
experiment: ""